spring:
  application:
    name: may-2024-spring-boot
  datasource:
    url: "jdbc:mysql://localhost:3306/asd?createDatabaseIfNotExist=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost/carservice
  mail:
    host: smtp.gmail.com
    port: 587
    username: owu.test.email@gmail.com
    password: ainuypabljetuhxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
